:sites:
  - 
    :name: Bloomfield-Garfield Corporation
    :abbr: BGC
    :base_ip: '10.96'
    :address: '5321 Penn Ave'
    :phone: 412-441-9833
  - 
    :name: Homewood YMCA
    :abbr: HY
    :base_ip: '10.32'
    :address: '7140 Bennett St'
    :phone: 412-243-2900
  - 
    :name: Hill Top YMCA
    :abbr: HT
    :base_ip: '10.64'
    :address: '500 Brownsville Rd'
    :phone: 412-223-6851
  - 
    :name: Hill House Association
    :abbr: HH
    :base_ip: '10.128'
    :address: '1860 Center Ave'
    :phone: 412-281-8483

:form:
  :gender:
    Male: M
    Female: F
    Other: O
  :ethnicity:
    Black: B
    White: W
    Native American: NA
    Asian / Pacific Islanders: API
    Hispanic: H
    Bi-Racial: BR
    Other: O
  :household_numbers:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 0
  :household_incomes:
    - 11000
    - 15000
    - 18000
    - 22000
    - 26000
    - 30000
    - 33000
    - 37000
    - 0
  :education_levels:
    - In School
    - High School Graduate
    - Attended College or Technical School
    - Associates or Technical Degree
    - College Graduate
    - Advanced Degree
  :clearance_levels:
    - User
    - Coordinator
    - Manager

:ldap:
  :host: '10.96.0.12'
  :port: 389
  :auth:
    :username: 'cn=administrator, cn=users, dc=users, dc=pghconnects, dc=org'
    :password: 'YaphA3uc'
    :method: :simple

:administrators:
  -
    :first: Justin
    :last: Davis
    :registered_at: BGC
    :password: YaphA3uc
    :password_confirmation: YaphA3uc
    
