sites:
  - 
    !ruby/sym name: Bloomfield-Garfield Corporation
    !ruby/sym abbr: BGC
    !ruby/sym base_ip: '10.96'
    !ruby/sym address: BGC
    !ruby/sym phone: 123-456-7890
  - 
    !ruby/sym name: Homewood YMCA
    !ruby/sym abbr: HY
    !ruby/sym base_ip: '10.32'
    !ruby/sym address: HW
    !ruby/sym phone: 123-456-7890
  - 
    !ruby/sym name: Hill Top YMCA
    !ruby/sym abbr: HT
    !ruby/sym base_ip: '10.64'
    !ruby/sym address: HT
    !ruby/sym phone: 123-456-7890
  - 
    !ruby/sym name: Hill House Association
    !ruby/sym abbr: HH
    !ruby/sym base_ip: '10.128'
    !ruby/sym address: HH
    !ruby/sym phone: 123-456-7890

form:
  gender:
    Male: M
    Female: F
    Other: O
  ethnicity:
    Black: B
    White: W
    Native American: NA
    Asian / Pacific Islanders: API
    Hispanic: H
    Bi-Racial: BR
    Other: O
  household_numbers:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 0
  household_incomes:
    - 11000
    - 15000
    - 18000
    - 22000
    - 26000
    - 30000
    - 33000
    - 37000
    - 0
  education_levels:
    - No High School Diploma
    - High School Graduate
    - GED
    - Some College
    - College Graduate
    - Technical School Graduate
    - Post-College Graduate
