resolutions:
  10.96: BGC
  10.32: HY
  10.64: HT
  10.128: HH

abbrs:
  BGC: Bloomfield-Garfield Corporation
  HY: Homewood YMCA
  HT: Hill Top YMCA
  HH: Hill House Association

reverse_abbrs:
  Bloomfield-Garfield Corporation: BGC
  Homewood YMCA: HY
  Hill Top YMCA: HT
  Hill House Association: HH
